import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

// 🌍 Currency mapping
const currencyMap = {
    "₹": "INR",
    "$": "USD",
    "€": "EUR",
};

// 💰 Formatter (FIXED)
const formatCurrency = (amount, symbol = "₹") => {
    return new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: currencyMap[symbol] || "INR",
    }).format(amount);
};

export const exportToPDF = (
    expenses,
    summary,
    selectedEvent,
    currency = "₹"
) => {
    const doc = new jsPDF();

    const { totalCredit, totalExpense, balance } = summary;

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // 🎨 COLORS
    const PRIMARY = [79, 70, 229];
    const SUCCESS = [34, 197, 94];
    const DANGER = [239, 68, 68];

    // 💧 WATERMARK
    const addWatermark = () => {
        const logo = new Image();
        logo.src = "/EXP-Monochrome-logo.png";

        doc.saveGraphicsState();
        doc.setGState(new doc.GState({ opacity: 0.04 }));

        doc.addImage(
            logo,
            "PNG",
            pageWidth / 2 - 50,
            pageHeight / 2 - 50,
            100,
            100
        );

        doc.restoreGraphicsState();
    };

    addWatermark();

    // 🟣 HEADER BAR
    doc.setFillColor(...PRIMARY);
    doc.rect(0, 0, pageWidth, 30, "F");

    // 🧾 LOGO
    const logo = new Image();
    logo.src = "/EXP-Logo.png";
    doc.addImage(logo, "PNG", 14, 8, 14, 14);

    // 🧾 TITLE
    doc.setFontSize(16);
    doc.setTextColor(255);
    doc.text("Expense Report", 34, 18);

    // 🧾 META
    doc.setFontSize(10);
    doc.setTextColor(230);
    doc.text(`Event: ${selectedEvent}`, pageWidth - 60, 12);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 60, 18);

    // 🔲 SUMMARY CARDS
    const startY = 40;

    const drawCard = (x, label, value, color) => {
        doc.setFillColor(248, 250, 252);
        doc.roundedRect(x, startY, 55, 25, 4, 4, "F");

        doc.setFontSize(9);
        doc.setTextColor(120);
        doc.text(label, x + 5, startY + 8);

        doc.setFontSize(12);
        doc.setTextColor(...color);
        doc.text(formatCurrency(value, currency), x + 5, startY + 18);
    };

    drawCard(14, "Credit", totalCredit, SUCCESS);
    drawCard(74, "Expense", totalExpense, DANGER);
    drawCard(134, "Balance", balance, PRIMARY);

    // 📊 TABLE DATA (FIXED)
    const tableData = expenses.map((e) => [
        new Date(
            e.createdAt?.seconds
                ? e.createdAt.seconds * 1000
                : Date.now()
        ).toLocaleDateString(),
        e.description,
        e.event || "general",
        e.type === "credit"
            ? `+${formatCurrency(e.amount, currency)}`
            : `-${formatCurrency(e.amount, currency)}`,
    ]);

    // 📊 TABLE
    autoTable(doc, {
        startY: startY + 35,
        head: [["Date", "Description", "Event", "Amount"]],
        body: tableData,

        styles: {
            fontSize: 10,
            cellPadding: 5,
        },

        headStyles: {
            fillColor: PRIMARY,
            textColor: 255,
            fontStyle: "bold",
        },

        alternateRowStyles: {
            fillColor: [248, 250, 252],
        },

        didParseCell: function (data) {
            if (data.column.index === 3) {
                if (data.cell.raw.includes("+")) {
                    data.cell.styles.textColor = SUCCESS;
                } else {
                    data.cell.styles.textColor = DANGER;
                }
            }
        },
    });

    // 💧 WATERMARK ALL PAGES
    const pageCount = doc.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        addWatermark();
    }

    // 🧾 FOOTER
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text(
        "Generated by Expense Tracker • Smart Finance App",
        14,
        pageHeight - 10
    );

    // 💾 SAVE
    doc.save(`Expense_Report_${selectedEvent}.pdf`);
};